### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by mortum5** [FrontendSophie/hexo-infinite-scroll#2]
Hello.

I'm trying to use your plugins with landscape theme. I add next string to /landscape/layout/_partial/head.ejs
 ```html
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>                                                          
 <link rel="stylesheet" href="http://osly086qe.bkt.clouddn.com/hexo-infinite-scroll-v1.0.1.min.css">                                              
 <script src="http://osly086qe.bkt.clouddn.com/hexo-infinite-scroll-v1.0.3.min.js"></script>                                                      
 <script>infiniteScroll();</script>
```
And after that i can scroll down to bottom of page and see page buttons; in console i just catch trigger events and nothing more.

If i change per_page to 0, i see all post at once.

Do you have any suggestions?

**Comment by FrontendSophie** [comment]
Hello @mortum5 ,

Just checked theme landscape, the reason why this plugin does not work is landscape uses  className `.article` for each post instead of `.post`.

Could you please try code below for initialization ?
 ```    
infiniteScroll({
      item: '.article'
});
```

BTW, I will improve this plugin in the coming days to make it more user friendly and well-documented.

In case any further issues, please do not hesitate to inform me, thanks 🙂

**Comment by mortum5** [comment]
Hello @FrontendSophie ,

You are right, now it works perfect.

Thank you!
